from . import contractor_images
from . import hr_contractor_agreement_type
from . import hr_contractor_phone
from . import hr_engagement
from . import inherit_hr_department
from . import inherit_hr_employee
from . import inherit_hr_employee_category
from . import inherit_project_project
from . import inherit_project_task
from . import inherit_res_partner_address
from . import inherit_res_partner_contact
